import Head from 'next/head';
import RunGame from '../components/main/RunGame';
import imageTicTacToe from '../images/TicTacToe.png';
import styles from '../styles/Home.module.css';

const Home: React.FC = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>TicTacToe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={imageTicTacToe} />
      </Head>

      <RunGame />
    </div>
  )
}

export default Home;
