import Head from 'next/head';
import { useContext } from 'react';
import CongratulationsScreen from '../components/screens/CongratulationsScreen';
import DrawScreen from '../components/screens/DrawScreen';
import GameScreen from '../components/screens/GameScreen';
import InitialScreen from '../components/screens/InitialScreen';
import { ticTacToeContext } from '../contexts/TicTacToeContext';
import imageTicTacToe from '../images/TicTacToe.png';
import styles from '../styles/Home.module.css';

const Home: React.FC = () => {
  const {
    isCongratulations,
    isDraw,
    gameStage
  } = useContext(ticTacToeContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>TicTacToe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={imageTicTacToe} />
      </Head>

      <main>
        {
          gameStage === 'notStarted' ?

            <InitialScreen />
            :
            (
              isDraw ?
                <DrawScreen /> : <GameScreen />
            )
        }
      </main>
    </div>
  )
}

export default Home;
